version: '3.6'
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: always
    depends_on:
      - ustreamer
      - tinypilot
    ports:
      - "8900:8900"
    volumes:
      - ./nginx/kvn.conf.template:/etc/nginx/nginx.conf  # nginx 설정 파일을 직접 nginx.conf로 마운트

  ustreamer:
   # build:
   #   context: ./images/ustreamer/
    image: haru2/ustreamer-docker:latest
    container_name: ustreamer
    restart: always
    ports:
      - "8001:8001"
    devices:
      - /dev/video0:/dev/video0
    command: ["ustreamer", "--host=0.0.0.0", "--resolution=2560x1600", "--port=8001", "/dev/video0"] #1280x720

  tinypilot:
   # build:
   #   context: ./images/tinypilot/
    image: haru2/tinypilot-docker:latest
    container_name: tinypilot
    restart: always
    ports:
      - "8000:8000"
    devices:
     - /dev/hidg0:/dev/hidg0
     - /dev/hidg1:/dev/hidg1
    volumes:
      - ./config/config.py:/opt/tinypilot/config.py  # Tinypilot 설정 파일 마운트

    command: ["python3", "/opt/tinypilot/app/main.py"]
